// modules/demo-with-react/src/App.tsx
import './App.css'
import { sleep } from './lib/sleep'
import { RegistrationForm } from './RegistrationForm/Component'

function App() {
  return (
    <div className="app">
      <h2>Registration form</h2>
      <p>
        Build with <a href="https://reactjs.org/">React</a> and{' '}
        <a href="https://sacdenoeuds.github.io/unhoax/">unhoax</a> 😉
      </p>
      <RegistrationForm
        onRegister={async (values) => {
          await sleep(750)
          console.info('submitted:', values)
        }}
      />
    </div>
  )
}

export default App

// demos/flemme-vue/multi-step-registration-form/App.vue
<script setup lang="ts">
import { sleep } from '../lib/sleep'
import RegistrationForm from './RegistrationForm.vue'
import { FormValues } from './useRegistrationForm'

async function register(values: FormValues) {
  await sleep(750)
  console.info('submitted:', values)
}
</script>

<template>
  <div class="app">
    <h2>Registration form</h2>
    <RegistrationForm :submit="register" />
  </div>
</template>
<style>
form {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}
form footer {
  display: flex;
  gap: 0.5rem;
  & button {
    flex: 1;
  }
}
</style>
